version: "3"
services:
  getlist:
    build:
      context: ./
      dockerfile: ./dockerFile/GetListDockerfile
    volumes:
      - ./:/app
  calculate:
    build:
      context: ./
      dockerfile: ./dockerFile/CalculateDockerfile
    volumes:
      - ./:/app
  updateprice:
    build:
      context: ./
      dockerfile: ./dockerFile/UpdatePriceDockerfile
    volumes:
      - ./:/app
  checkbuyable:
    build:
      context: ./
      dockerfile: ./dockerFile/CheckBuyAbleDockerfile
    volumes:
      - ./:/app
